version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
        environment:
          PGHOST: 127.0.0.1
          POSTGRES_DB: circle_test
          POSTGRES_HOST: localhost
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          SPRING_DATASOURCE_URL: jdbc:postgresql://root@localhost/circle_test

      - image: cimg/postgres:13.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test