version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
      - image: cimg/postgres:13.5
        environment:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=GameBoyT_fish-n-chill

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build-and-test:
          context: SonarCloud
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: heroku
